-- MySQL Script generated by MySQL Workbench
-- 07/11/15 19:05:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `userId` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`),
  UNIQUE INDEX `userId_UNIQUE` (`userId` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultant` (
  `consultantId` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(45) NULL,
  `user_userId` INT NOT NULL,
  PRIMARY KEY (`consultantId`),
  INDEX `fk_consultant_user_idx` (`user_userId` ASC),
  CONSTRAINT `fk_consultant_user`
    FOREIGN KEY (`user_userId`)
    REFERENCES `mydb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partner` (
  `partnerId` INT NOT NULL AUTO_INCREMENT,
  `website` VARCHAR(45) NOT NULL,
  `letterOfIntrest` BLOB NULL,
  `user_userId` INT NOT NULL,
  `workArea` VARCHAR(45) NOT NULL,
  `projectDetail` BLOB NOT NULL,
  PRIMARY KEY (`partnerId`),
  INDEX `fk_partner_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_partner_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `mydb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`onSiteManager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`onSiteManager` (
  `onSiteManagerId` INT NOT NULL AUTO_INCREMENT,
  `user_userId` INT NOT NULL,
  `designation` VARCHAR(45) NULL,
  PRIMARY KEY (`onSiteManagerId`),
  INDEX `fk_onSiteManager_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_onSiteManager_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `mydb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(1000) NULL,
  `type` VARCHAR(45) NOT NULL,
  `remark` VARCHAR(500) NULL,
  PRIMARY KEY (`questionId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`area` (
  `areaId` INT NOT NULL AUTO_INCREMENT,
  `proneTo` VARCHAR(45) NULL,
  `population` VARCHAR(45) NULL,
  `economy` DECIMAL(10,0) NULL,
  `zone` VARCHAR(45) NULL,
  PRIMARY KEY (`areaId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solution` (
  `user_userId` INT NOT NULL,
  `question_questionId` INT NOT NULL,
  `solution` VARCHAR(1000) NULL,
  PRIMARY KEY (`user_userId`, `question_questionId`),
  INDEX `fk_user_has_question_question1_idx` (`question_questionId` ASC),
  INDEX `fk_user_has_question_user1_idx` (`user_userId` ASC),
  CONSTRAINT `fk_user_has_question_user1`
    FOREIGN KEY (`user_userId`)
    REFERENCES `mydb`.`user` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_question_question1`
    FOREIGN KEY (`question_questionId`)
    REFERENCES `mydb`.`question` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`school` (
  `schoolId` INT NOT NULL AUTO_INCREMENT,
  `schoolName` VARCHAR(100) NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `resourceRequired` VARCHAR(45) NULL,
  `scale` VARCHAR(45) NULL,
  `noOfStudents` VARCHAR(45) NULL,
  `capacity` VARCHAR(45) NULL,
  `area_areaId` INT NOT NULL,
  `solution_user_userId` INT NOT NULL,
  `solution_question_questionId` INT NOT NULL,
  PRIMARY KEY (`schoolId`),
  INDEX `fk_school_area1_idx` (`area_areaId` ASC),
  INDEX `fk_school_solution1_idx` (`solution_user_userId` ASC, `solution_question_questionId` ASC),
  CONSTRAINT `fk_school_area1`
    FOREIGN KEY (`area_areaId`)
    REFERENCES `mydb`.`area` (`areaId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_school_solution1`
    FOREIGN KEY (`solution_user_userId` , `solution_question_questionId`)
    REFERENCES `mydb`.`solution` (`user_userId` , `question_questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`project` (
  `projectId` INT NOT NULL AUTO_INCREMENT,
  `projectEstimatedCost` INT(10) NOT NULL,
  `actualCost` INT(10) NOT NULL,
  `efficiencyIncrease` VARCHAR(45) NOT NULL,
  `projectDetail` VARCHAR(1000) NULL,
  `school_schoolId` INT NOT NULL,
  `onSiteManager_onSiteManagerId` INT NOT NULL,
  `startDate` DATE NOT NULL,
  `completionDate` DATE NOT NULL,
  PRIMARY KEY (`projectId`),
  INDEX `fk_project_school1_idx` (`school_schoolId` ASC),
  INDEX `fk_project_onSiteManager1_idx` (`onSiteManager_onSiteManagerId` ASC),
  CONSTRAINT `fk_project_school1`
    FOREIGN KEY (`school_schoolId`)
    REFERENCES `mydb`.`school` (`schoolId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_project_onSiteManager1`
    FOREIGN KEY (`onSiteManager_onSiteManagerId`)
    REFERENCES `mydb`.`onSiteManager` (`onSiteManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`report` (
  `reportid` INT NOT NULL,
  `reportinfo` VARCHAR(45) NULL,
  `expenditure` INT NOT NULL,
  `completion` INT NULL,
  `onSiteManager_onSiteManagerId` INT NOT NULL,
  PRIMARY KEY (`reportid`),
  INDEX `fk_report_onSiteManager1_idx` (`onSiteManager_onSiteManagerId` ASC),
  CONSTRAINT `fk_report_onSiteManager1`
    FOREIGN KEY (`onSiteManager_onSiteManagerId`)
    REFERENCES `mydb`.`onSiteManager` (`onSiteManagerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
